import {CompanySettingOfUpdateCompanySettingWithChartOfAccountRequest} from "./CompanySettingOfUpdateCompanySettingWithChartOfAccountRequest";

export interface UpdateBatchCompanySettingWithChartOfAccountRequest {
    companySettings: CompanySettingOfUpdateCompanySettingWithChartOfAccountRequest[]
}